name: Check for broken links

on: [ push ]

jobs:
  mintlify-broken-links:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: "Install deps"
        run: |
          npm i -g mintlify
      - name: "Check for broken links"
        run: |
          mintlify broken-links